app.title=Book Store Demo Template
app.company_name=Book Store

# Spring backend
api.base_url=http://localhost:8082

api.endpoint.auth.login=/api/auth/login
api.endpoint.products=/api/products
api.endpoint.products.options=/api/products/options
api.endpoint.products.next_id=/api/products/next-id
api.endpoint.orders=/api/orders
api.endpoint.files.images=/api/files/images
